version: "3.9"

services:
  backend:
    build: ./backend
    container_name: shopstack-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=sqlite:///./database.db
    env_file:
      - ./backend/.env
  
  frontend:
    build: ./frontend
    container_name: shopstack-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend